import numpy as np
import matplotlib.pyplot as plt

v = np.array([0, 1])
M = np.array([[1.02, 0.095], [-0.095, 1.02]])
points = [v]
for _ in range(250):
    v = M.dot(v)
    points.append(v)
points = np.array(points)
plt.plot(points[:, 0], points[:, 1], marker='o', linestyle='-', markersize=3, linewidth=1)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Trace of Points Generated by Repeated Matrix Multiplications')
plt.grid(True)
plt.show()
